version: '3'
services:

  web:
    container_name: web
    image: mkh1213/spring-docker-study
    expose:
      - 8080
    ports:
      - "8080:8080"

  nginx:
    container_name: nginx
    image: mkh1213/spring-docker-study-nginx
    ports:
      - "80:80"
    depends_on:
      - web